create database INVOICE;
use INVOICE;
show databases;
create table student(id int primary key auto_increment,name varchar(20),age int,city varchar(30));
desc student;
alter table student add dob date;
desc student;
alter table student modify dob year;
desc student;
alter table student drop city;
desc student;
create table CUSTOMER(cust_id int primary key auto_increment,address varchar(30),city varchar(20),ph_no int);
desc CUSTOMER;
create table PRODUCT(p_id int primary key auto_increment,p_name varchar(20),price int default'0');
desc PRODUCT;
create table invoice_master(inv_id int primary key auto_increment,cust_id int,constraint cust_id foreign key(cust_id)references CUSTOMER(cust_id),inv_date date);
desc invoice_master;
create table invoice_item(inv_id int,constraint inv_id foreign key(inv_id)references invoice_master(inv_id),p_id int,constraint p_id foreign key(p_id)references product(p_id),quantity int);
show tables;
alter table CUSTOMER add cust_name varchar(20);
desc customer;
truncate student;
desc student;
truncate table product;
desc product;
drop table student;
show tables;